# Generated by Django 3.2.5 on 2021-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='best_discount',
            field=models.IntegerField(default=0),
        ),
    ]
