# Generated by Django 3.2.5 on 2021-07-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.URLField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='personal_site',
            field=models.URLField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Restaurants.location'),
        ),
    ]
