# Generated by Django 3.2.5 on 2021-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_auto_20210730_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField(blank=True, default='None', max_length=100, null=True)),
                ('personal_site', models.URLField(blank=True, default='None', max_length=100, null=True)),
                ('minimum_value_command', models.FloatField(default=0)),
                ('phoneNumber', models.CharField(default='Missing', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
    ]
