# Generated by Django 3.2.5 on 2021-10-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_restaurant_best_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='likes',
        ),
    ]
