# Generated by Django 3.2.5 on 2021-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_auto_20210731_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.URLField(default='None', max_length=100),
        ),
    ]
