# Generated by Django 3.2.5 on 2021-08-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_auto_20210805_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='None@yahoo.com', max_length=100),
        ),
    ]
