# Generated by Django 3.2.5 on 2021-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0008_auto_20210805_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
