# Generated by Django 3.2.5 on 2021-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0009_restaurant_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
