# Generated by Django 3.2.5 on 2021-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0010_alter_restaurant_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
