# Generated by Django 3.2.5 on 2021-08-14 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurants', '0013_restaurant_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Likes',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
