# Generated by Django 3.2.5 on 2021-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0003_alter_basecustomuser_cnp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='cnp',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
