# Generated by Django 3.2.5 on 2021-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0008_rename_active_basecustomuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
