# Generated by Django 3.2.5 on 2021-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0010_auto_20210807_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecustomuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='basecustomuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
