# Generated by Django 3.2.5 on 2021-08-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No bio present', max_length=255),
        ),
    ]
