# Generated by Django 3.2.5 on 2021-09-03 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(5, 'Great 5/5'), (4, 'Good 4/5'), (3, 'Mediocre 3/5'), (2, 'Bad 2/5'), (1, 'No Type 1/5')], default=3)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(max_length=400)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='dislikes_reviews', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes_reviews', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='Restaurants.restaurant')),
            ],
        ),
    ]
