# Generated by Django 3.2.5 on 2021-08-04 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0002_auto_20210804_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(choices=[(5, 'Great 5/5'), (4, 'Good 4/5'), (3, 'Mediocre 3/5'), (2, 'Bad 2/5'), (1, 'No Type 1/5')], default=3),
        ),
    ]
