# Generated by Django 3.2.5 on 2021-10-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0011_menuitem_position'),
        ('Restaurants', '0003_auto_20211016_2202'),
        ('RatingsItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_restaurant', to='Restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Food.menuitem'),
        ),
    ]
