# Generated by Django 3.2.5 on 2021-09-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A La Carte Menu', 'a la carte menu'), ('Static Menu', 'static menu'), ('Du Jour Menu', 'du jour menu'), ('Cycle Menu', 'cycle menu'), ('Fixed Menu', 'fixed_menu')], default='Fixed Menu', max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Section', max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Menu.menu')),
            ],
        ),
    ]
