# Generated by Django 3.2.5 on 2021-09-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_alter_menuitem_section'),
        ('Menu', '0002_auto_20210916_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
