# Generated by Django 3.2.5 on 2021-09-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
        ('Menu', '0003_delete_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='Restaurants.restaurant'),
        ),
    ]
