# Generated by Django 3.2.5 on 2021-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('A La Carte Menu', 'a la carte menu'), ('Static Menu', 'static menu'), ('Du Jour Menu', 'du jour menu'), ('Cycle Menu', 'cycle menu'), ('Fixed Menu', 'fixed_menu')], default='Fixed Menu', max_length=100),
        ),
    ]
