# Generated by Django 3.2.5 on 2021-10-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_restaurant_best_discount'),
        ('Menu', '0004_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Restaurants.restaurant'),
        ),
    ]
