# Generated by Django 3.2.5 on 2021-09-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_adults', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('photo', models.ImageField(default='images/Salam.jpg', upload_to='images/')),
                ('ingredients', models.ManyToManyField(to='Food.Ingredients')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Menu.section')),
            ],
        ),
    ]
