# Generated by Django 3.2.5 on 2021-08-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menu_restaurant'),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_adults', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('ingredients', models.ManyToManyField(to='Food.Ingredients')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='section',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
