# Generated by Django 3.2.5 on 2021-08-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_menu_type'),
        ('Food', '0002_auto_20210803_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Menu.section'),
        ),
    ]
