# Generated by Django 3.2.5 on 2021-09-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_alter_menuitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(to='Food.Ingredients'),
        ),
    ]
