# Generated by Django 3.2.5 on 2021-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_menuitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(default='/media/images/Salam.jpg', upload_to='images/'),
        ),
    ]
