# Generated by Django 3.2.5 on 2021-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredients', '0001_initial'),
        ('Food', '0004_alter_menuitem_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(to='Ingredients.Ingredient'),
        ),
    ]
