# Generated by Django 3.2.5 on 2021-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_menuitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(default='images/Salam.jpg', upload_to='images/'),
        ),
    ]
