# Generated by Django 3.2.5 on 2021-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredients', '0001_initial'),
        ('Food', '0005_auto_20210921_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='Ingredients.Ingredient'),
        ),
    ]
