# Generated by Django 3.2.5 on 2021-10-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_alter_menuitem_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='Descriptions are hard', max_length=250),
        ),
    ]
