# Generated by Django 3.2.5 on 2021-10-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_auto_20211003_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/Salam.jpg', upload_to='images/food/'),
        ),
    ]
