# Generated by Django 3.2.5 on 2021-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/Salam.jpg', upload_to='food/'),
        ),
    ]
