# Generated by Django 3.2.5 on 2021-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0010_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
